import { useEffect, useState } from 'react';
import { addDoc, collection, doc, onSnapshot, orderBy, query, serverTimestamp, updateDoc } from 'firebase/firestore';
import { auth, db } from '../services/firebase';

type Contact = { id: string; name: string; phone: string; optIn: boolean; optedOut: boolean; active: boolean };

export default function Contacts() {
  const [contacts, setContacts] = useState<Contact[]>([]);
  const [form, setForm] = useState({ name: '', phone: '', optIn: false });
  const [error, setError] = useState('');
  const userId = auth.currentUser?.uid;
  useEffect(() => userId ? onSnapshot(query(collection(db, 'users', userId, 'contacts'), orderBy('createdAt', 'desc')), (snapshot) => setContacts(snapshot.docs.map((item) => ({ id: item.id, ...item.data() } as Contact))), () => setError('Não foi possível carregar os contatos.')) : undefined, [userId]);
  const createContact = async (event: React.FormEvent) => { event.preventDefault(); if (!userId) return; try { await addDoc(collection(db, 'users', userId, 'contacts'), { ...form, active: true, optedOut: false, createdAt: serverTimestamp(), updatedAt: serverTimestamp() }); setForm({ name: '', phone: '', optIn: false }); } catch { setError('Não foi possível salvar o contato.'); } };
  const optOut = async (contact: Contact) => { if (userId) await updateDoc(doc(db, 'users', userId, 'contacts', contact.id), { optedOut: true, optIn: false, updatedAt: serverTimestamp() }); };
  return <div><div style={{ marginBottom: 24 }}><p style={{ color: 'var(--green-dark)', fontWeight: 700, fontSize: 12, letterSpacing: '.08em' }}>BASE DE CONTATOS</p><h1 style={{ marginTop: 6 }}>Contatos</h1><p style={{ color: 'var(--muted)', marginTop: 8 }}>Gerencie consentimento e opt-out em um só lugar.</p></div>{error && <div className="card" style={{ color: '#bd3b36', marginBottom: 16 }}>{error}</div>}<div className="grid-2"><form className="card" onSubmit={createContact}><h2 style={{ fontSize: 18 }}>Adicionar contato</h2><label className="label">Nome</label><input className="input" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required /><label className="label">WhatsApp</label><input className="input" value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} placeholder="5511999999999" required /><label style={{ display: 'flex', gap: 8, alignItems: 'center', marginTop: 16, fontSize: 13 }}><input type="checkbox" checked={form.optIn} onChange={(event) => setForm({ ...form, optIn: event.target.checked })} /> Possui consentimento</label><button className="btn btn-primary" style={{ marginTop: 20 }}>Salvar contato</button></form><div className="card"><h2 style={{ fontSize: 18, marginBottom: 16 }}>Contatos cadastrados ({contacts.length})</h2>{contacts.length === 0 ? <p style={{ color: 'var(--muted)' }}>Nenhum contato cadastrado.</p> : <div style={{ display: 'grid', gap: 10 }}>{contacts.map((contact) => <div key={contact.id} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 12, padding: 12, background: 'var(--bg)', borderRadius: 8 }}><div><strong>{contact.name}</strong><p style={{ color: 'var(--muted)', fontSize: 13, marginTop: 3 }}>{contact.phone}</p></div>{contact.optedOut ? <span style={{ color: '#bd3b36', fontSize: 12 }}>Opt-out</span> : <button className="btn btn-outline" onClick={() => optOut(contact)} style={{ padding: '7px 10px', fontSize: 12 }}>Opt-out</button>}</div>)}</div>}</div></div></div>;
}
